### ISSUE TITLE
Bug: Annotations can't be of annotationType "ink"

### ISSUE THREAD

**Issue by volker-fr** [mgmeyers/obsidian-zotero-integration#110]
The plugin can't handle handwritten nodes on PDF import.

PDF files was only annotated with Zotero 6's new PDF editor, no external editor.

Root cause is that in the function `convertNativeAnnotation` the position is taken, but not available in the expected format. Line culprit: https://github.com/mgmeyers/obsidian-zotero-integration/blob/main/src/bbt/export.ts#L88
```
   const rect = annotation.annotationPosition.rects[0];
```

Data blob example that works:
```
annotationAuthorName: ""
annotationComment: ""
annotationPageLabel: "30"
annotationPosition:
   pageIndex: 41
   rects: (5) [Array(4), Array(4), Array(4), Array(4), Array(4)]
   [[Prototype]]: Object
annotationSortIndex: "00041|000143|00108"
annotationText: "text snippet higlighted"
annotationType: "highlight"
...
```

Data blob example that doesn't work. You can see how there is no `annotationPosition.rects` value, but only paths.
```
annotationAuthorName: ""
annotationColor: "#ff6666"
annotationComment: ""
annotationPageLabel: "30"
annotationPosition:
   pageIndex: 41
   paths: (8) [Array(606), Array(614), Array(614), Array(614), Array(614), Array(614), Array(614), Array(614)]
   width: 2
   [[Prototype]]: Object
annotationSortIndex: "00041|000172|00119"
annotationType: "ink"
```
